### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Ogaday** [thalesians/tsa#1]
I would suggest adding a `README` file with (preferably) guides for:

* Introduction & motivation
* Install
* Quickstart / link to the notebooks
* Contributing

This will make it a lot more easy for others not familiar with the project to use it and contribute.

**Comment by sydx** [comment]
This is a great point, @Ogaday . Will add this shortly.

**Comment by sydx** [comment]
Checked in the initial README file. Many thanks for this suggestion, @Ogaday .
